%define TOK_EOF          0
%define TOK_UNKNOWN      1
%define TOK_NEWLINE      2

%define TOK_IDENT        3
%define TOK_NUMBER       4
%define TOK_CHAR         5
%define TOK_STRING       6

%define TOK_LBRACE       7
%define TOK_RBRACE       8
%define TOK_LPAREN       9
%define TOK_RPAREN       10
%define TOK_LBRACK       11
%define TOK_RBRACK       12
%define TOK_COMMA        13

%define TOK_EQUAL        14
%define TOK_EQEQ         15

%define TOK_PLUS         16
%define TOK_MINUS        17
%define TOK_STAR         18
%define TOK_SLASH        19

%define TOK_LT           20
%define TOK_GT           21
%define TOK_LTE          22
%define TOK_GTE          23

%define TOK_ARROW        24

%define TOK_IF           25
%define TOK_ELSE         26
%define TOK_REP          27
%define TOK_RET          28

%define TOK_INT8         29
%define TOK_NAT8         30
%define TOK_INT16        31
%define TOK_NAT16        32
%define TOK_INT32        33
%define TOK_NAT32        34
%define TOK_INT64        35
%define TOK_NAT64        36
%define TOK_BOOL         37